export type DiscoveryPageData = {
  slug: string;
  path: string;
  eyebrow: string;
  title: string;
  seoTitle: string;
  description: string;
  intro: string;
  highlights: readonly string[];
  sections: readonly (readonly [string, string])[];
};

export const chorePages = {
  cleaning: {
    slug: "cleaning",
    path: "/chores/cleaning/",
    eyebrow: "Cleaning chores",
    title: "Find local help for the cleaning that keeps piling up.",
    seoTitle: "Local Cleaning Help & Flexible Cleaning Jobs | Chorezy",
    description: "Join the Chorezy U.S. waitlist for nearby cleaning help and flexible chores such as dusting, sweeping, organizing, and deep cleaning.",
    intro: "Chorezy is being built to help busy households turn a vague cleaning list into a clearly scoped chore—and help eligible people nearby choose work that fits their time and skills.",
    highlights: ["Routine and one-time cleaning", "Scope, rooms, timing, and checklist upfront", "Nearby opportunities for eligible helpers"],
    sections: [
      ["Describe the result you need", "Posters can list the rooms, surfaces, supplies, priorities, timing, photos, and budget so a helper can understand the job before making an offer."],
      ["Choose cleaning work that fits", "Eligible helpers can review the scope and decide whether the location, schedule, and expectations are a good match—without automatic assignment."],
      ["Keep the handoff organized", "In-app details, communication, progress updates, completion proof, payment, and reviews are being designed to stay connected to the chore."],
    ],
  },
  "yard-care": {
    slug: "yard-care",
    path: "/chores/yard-care/",
    eyebrow: "Yard care chores",
    title: "Find yard work nearby—or earn by helping outdoors.",
    seoTitle: "Yard Work Near Me: Local Help & Jobs | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local yard work, lawn cleanup, leaf removal, watering, and other neighborhood outdoor chores.",
    intro: "Chorezy is being built to help households describe outdoor work clearly and let eligible local helpers decide which nearby opportunities fit their skills and schedule.",
    highlights: ["Lawn and garden cleanup", "Leaves, watering, and light outdoor help", "Clear timing, budget, checklist, and photos"],
    sections: [
      ["For busy households", "Turn the outdoor jobs sitting on your list into a clear chore with timing, budget, photos, and a checklist. Compare offers before choosing a helper."],
      ["For local helpers", "Browse eligible yard-care opportunities close to home and make an offer when the work, timing, and expectations suit you."],
      ["Designed for a clear handoff", "In-app details, communication, arrival updates, and completion records are being designed to keep both sides aligned."],
    ],
  },
  "pet-care": {
    slug: "pet-care",
    path: "/chores/pet-care/",
    eyebrow: "Pet care chores",
    title: "Make everyday pet help easier to arrange nearby.",
    seoTitle: "Local Pet Care Help & Chores | Chorezy",
    description: "Join the Chorezy U.S. waitlist for nearby pet care chores such as walks, feeding support, and routine pet help.",
    intro: "For families balancing work, school, and travel, small pet-care gaps can be hard to coordinate. Chorezy is being built around clear task details and eligible local help.",
    highlights: ["Dog walking and routine visits", "Feeding and simple care instructions", "Task details kept in one place"],
    sections: [
      ["Set expectations before the chore", "Posters can describe the pet, routine, timing, access instructions, budget, and any important context before selecting a helper."],
      ["Choose work that fits", "Eligible helpers can review the requirements and make an offer only when the task is a suitable match."],
      ["Safety is part of the flow", "Chorezy is designing identity, eligibility, in-app communication, reporting, and active-task safety tools into the marketplace."],
    ],
  },
  errands: {
    slug: "errands",
    path: "/chores/errands/",
    eyebrow: "Local errands",
    title: "Get help with local errands when the day is already full.",
    seoTitle: "Local Errand Help & Jobs | Chorezy",
    description: "Join the Chorezy U.S. waitlist to post eligible local errands or find nearby errand work as an Adult Helper.",
    intro: "Chorezy is being built for the practical jobs that consume time: local pickups, drop-offs, and other eligible errands with clear instructions and progress updates.",
    highlights: ["Local pickups and drop-offs", "Timing and checklist details", "Adult Helper opportunities"],
    sections: [
      ["For working parents and busy households", "Describe what needs to happen, where, and by when—then compare offers from eligible helpers instead of coordinating across multiple apps."],
      ["For Adult Helpers ages 18+", "Find nearby errand opportunities that fit your availability, review the requirements, and decide what you want to offer."],
      ["Know what is happening", "Arrival and progress updates are being designed to give posters a clearer view from acceptance through completion."],
    ],
  },
  "food-and-groceries": {
    slug: "food-and-groceries",
    path: "/chores/food-and-groceries/",
    eyebrow: "Food and grocery chores",
    title: "Make grocery runs and everyday food prep easier to arrange.",
    seoTitle: "Grocery Shopping & Meal Prep Help Nearby | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local grocery shopping, pickup, meal-prep, and everyday kitchen-help chores.",
    intro: "For working parents and busy households, food tasks can consume the time between work, school, and home. Chorezy is being built to make eligible grocery and kitchen help easier to describe and coordinate.",
    highlights: ["Grocery shopping and pickup", "Simple meal-prep and kitchen help", "Lists, timing, substitutions, and budget in one place"],
    sections: [
      ["Start with a useful list", "Posters can share the items, store or pickup location, timing, substitutions, access notes, kitchen scope, and budget before selecting a helper."],
      ["Know what the chore involves", "Eligible helpers can review the details before offering, including whether transportation, shopping, or basic food preparation is part of the request."],
      ["Keep updates with the task", "Communication, checklist progress, arrival and completion updates, receipts, and payment steps are part of the planned Chorezy flow."],
    ],
  },
  "tech-help": {
    slug: "tech-help",
    path: "/chores/tech-help/",
    eyebrow: "Local tech help",
    title: "Get nearby help with everyday devices and digital setup.",
    seoTitle: "Local Tech Help & Flexible Tech Chores | Chorezy",
    description: "Join the Chorezy U.S. waitlist for nearby help with device setup, apps, printers, Wi-Fi, and eligible smart-home chores.",
    intro: "Small technology problems can block an entire afternoon. Chorezy is being built to connect clear, eligible tech chores with nearby helpers who understand the request and choose to offer their time.",
    highlights: ["Phones, computers, printers, and apps", "Wi-Fi and eligible smart-home setup", "Clear device and access expectations"],
    sections: [
      ["Explain the problem before anyone arrives", "Posters can describe the device, goal, symptoms, timing, photos, and what has already been tried so helpers can judge whether the chore fits their experience."],
      ["Protect private information", "A tech-help chore should not require sharing passwords, verification codes, banking details, or unrestricted account access. Chorezy’s safety guidance will keep those boundaries visible."],
      ["Choose a suitable local helper", "Eligible helpers can review the task and make an offer when the issue matches their skills, with communication and completion records kept in the chore flow."],
    ],
  },
  "home-help": {
    slug: "home-help",
    path: "/chores/home-help/",
    eyebrow: "Help around the home",
    title: "Move the household list forward with local help.",
    seoTitle: "Household Chore Help Near You | Chorezy",
    description: "Join the Chorezy U.S. waitlist for cleaning help, organizing, moving assistance, and other eligible household chores nearby.",
    intro: "From one-off cleanup to repeating household tasks, Chorezy is being built to make the work, budget, timing, and helper offers easier to understand.",
    highlights: ["Cleaning and organizing help", "Light moving and household tasks", "One-time or repeating chores"],
    sections: [
      ["Post a chore with useful context", "Add the scope, checklist, photos or voice context, timing, location, and budget so helpers can assess the work before making an offer."],
      ["Compare before you choose", "Posters remain in control of which eligible helper they select. Chorezy is not designed to assign a stranger automatically."],
      ["Keep a completion record", "Task communication, completion proof, reviews, payments, and dispute support are being designed into a single chore flow."],
    ],
  },
  assembly: {
    slug: "assembly",
    path: "/chores/assembly/",
    eyebrow: "Assembly chores",
    title: "Turn boxed-up projects into clearly scoped local chores.",
    seoTitle: "Furniture Assembly Help & Local Assembly Jobs | Chorezy",
    description: "Join the Chorezy U.S. waitlist for nearby furniture assembly, DIY kit setup, shelving, and other eligible household assembly chores.",
    intro: "Chorezy is being built for practical assembly jobs that need clear instructions, the right tools, and a realistic amount of time—not a confusing chain of messages.",
    highlights: ["Furniture and flat-pack assembly", "DIY kits and eligible household setup", "Photos, instructions, tools, and scope upfront"],
    sections: [
      ["Show what is in the box", "Posters can add the product, instructions, photos, parts, available tools, workspace, timing, and budget so the scope is visible before offers arrive."],
      ["Match the chore to the helper", "Eligible helpers can decide whether the project suits their experience and tools. Electrical, structural, licensed, or otherwise restricted work should not be disguised as simple assembly."],
      ["Confirm the finished result", "Task communication, checklist progress, completion photos, payment, reviews, and support are being designed to remain attached to the chore."],
    ],
  },
  "car-care": {
    slug: "car-care",
    path: "/chores/car-care/",
    eyebrow: "Car care chores",
    title: "Find nearby help for the car-care jobs on your list.",
    seoTitle: "Local Car Washing & Car Care Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local car washing, vacuuming, window cleaning, trunk organizing, and other eligible car-care chores.",
    intro: "Chorezy is being built to make routine car care easier to scope locally—from a simple exterior wash to eligible maintenance help that requires an experienced Adult Helper.",
    highlights: ["Washing, vacuuming, and windows", "Clear tools, access, and location details", "Adult-only scope for eligible maintenance work"],
    sections: [
      ["Describe the vehicle and the result", "Posters can share the vehicle type, condition, available water or power, supplies, location, timing, photos, and budget before choosing a helper."],
      ["Keep the scope appropriate", "Young Helper chores can include suitable cleaning and organizing tasks. Maintenance, driving, powered equipment, and other higher-risk work may require an eligible Adult Helper."],
      ["Know what was completed", "The planned chore flow keeps instructions, communication, progress, completion proof, payment, and reviews connected to the task."],
    ],
  },
  "art-and-crafts": {
    slug: "art-and-crafts",
    path: "/chores/art-and-crafts/",
    eyebrow: "Art and craft chores",
    title: "Bring creative projects to life with a little local help.",
    seoTitle: "Local Arts, Crafts & Creative Project Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local help with crafts, cards, decorations, sewing, workshops, and other eligible creative projects.",
    intro: "Creative work still needs clear materials, timing, and expectations. Chorezy is being built to help people post practical art-and-craft chores and let eligible helpers choose projects that fit their skills.",
    highlights: ["Crafts, cards, and decorations", "Materials, references, and deadline upfront", "Simple projects and skilled creative help"],
    sections: [
      ["Show the creative direction", "Add reference images, dimensions, materials, the desired result, deadline, workspace, and budget so helpers can understand the project before offering."],
      ["Choose the right level of help", "Suitable projects can range from simple craft assistance to sewing, murals, or workshops, with eligibility depending on tools, setting, and experience."],
      ["Keep revisions clear", "In-app communication and progress updates are being designed to keep feedback and completion expectations attached to the original chore."],
    ],
  },
  sports: {
    slug: "sports",
    path: "/chores/sports/",
    eyebrow: "Sports and recreation chores",
    title: "Arrange nearby help for everyday sports and recreation.",
    seoTitle: "Local Sports, Coaching & Recreation Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for eligible local sports help, practice support, simple games, coaching, and event assistance.",
    intro: "Chorezy is being built for clearly described recreation tasks—from suitable outdoor play support to adult-led coaching or event help—with eligibility and safety expectations visible before anyone commits.",
    highlights: ["Practice, games, and activity support", "Location, equipment, and supervision details", "Eligibility based on the activity and risk"],
    sections: [
      ["Name the activity clearly", "Posters can describe the sport, participant ages, location, equipment, duration, supervision, experience requirements, and budget."],
      ["Match risk to eligibility", "Some simple activities may suit Young Helpers, while coaching, swimming, transportation, and higher-risk activities may require an eligible Adult Helper or may be restricted."],
      ["Keep safety expectations visible", "Communication, arrival information, active-task reporting, and emergency options are part of Chorezy’s planned task flow."],
    ],
  },
  tutoring: {
    slug: "tutoring",
    path: "/chores/tutoring/",
    eyebrow: "Tutoring chores",
    title: "Find nearby help for homework, reading, and learning goals.",
    seoTitle: "Local Tutoring & Homework Help Near You | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local homework help, reading practice, test preparation, language learning, and eligible tutoring chores.",
    intro: "Chorezy is being built to make learning help easier to describe—from peer homework support to adult-led tutoring—without hiding the subject, level, setting, or guardian expectations.",
    highlights: ["Homework and reading practice", "Subject, grade level, and goal upfront", "Peer help and adult tutoring options"],
    sections: [
      ["Start with the learning goal", "Posters can share the subject, level, assignment or goal, preferred setting, schedule, materials, guardian expectations, and budget."],
      ["Choose suitable experience", "Young Helpers may be a fit for eligible peer support, while test preparation, language teaching, or advanced subjects may call for an experienced Adult Helper."],
      ["Keep boundaries clear", "The planned flow keeps communication, schedule, task progress, payment, and reporting attached to the tutoring chore."],
    ],
  },
  "senior-care": {
    slug: "senior-care",
    path: "/chores/senior-care/",
    eyebrow: "Senior companionship and help",
    title: "Arrange thoughtful local help for everyday senior routines.",
    seoTitle: "Local Senior Companionship & Everyday Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for eligible senior companionship, meal help, light errands, housekeeping, and local routine support.",
    intro: "Chorezy is being designed for clearly scoped, non-medical everyday support. Families can explain the routine and eligibility needs before selecting a nearby helper.",
    highlights: ["Companionship and everyday routines", "Light errands, meals, and household help", "Non-medical scope stated clearly"],
    sections: [
      ["Explain the routine and setting", "Posters can share the expected activities, timing, mobility or access context, household preferences, emergency contact plan, and budget."],
      ["Separate companionship from clinical care", "Chorezy’s general chore marketplace is not a substitute for licensed medical, nursing, or emergency care. Restricted work should never be posted as a routine chore."],
      ["Choose eligibility deliberately", "Suitable reading, games, or light errands may differ from transportation, meal support, or extended companionship, which may require an eligible Adult Helper."],
    ],
  },
  events: {
    slug: "events",
    path: "/chores/events/",
    eyebrow: "Event-help chores",
    title: "Get extra hands for the details that make an event run.",
    seoTitle: "Local Event Setup, Teardown & Party Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local event setup, teardown, decorating, guest-list, refreshment, and eligible party-help chores.",
    intro: "Chorezy is being built to turn event-day needs into clear, time-bound chores so households, community groups, and local businesses can find suitable nearby help.",
    highlights: ["Setup, decorating, and teardown", "Guest lists and refreshment support", "Venue, timing, dress, and equipment details"],
    sections: [
      ["Build a practical event brief", "List the venue, arrival time, duration, responsibilities, dress expectations, lifting or equipment needs, contact person, and budget."],
      ["Split large events into clear chores", "Separate setup, guest support, refreshments, cleanup, and equipment work so helpers can offer for the part that fits their availability and experience."],
      ["Coordinate without message sprawl", "The planned flow keeps instructions, updates, completion, payment, and reviews connected to each event chore."],
    ],
  },
  photography: {
    slug: "photography",
    path: "/chores/photography/",
    eyebrow: "Photography chores",
    title: "Find local help capturing the moments and images you need.",
    seoTitle: "Local Photography, Video & Editing Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for nearby help with photos, short videos, albums, editing, and eligible event photography chores.",
    intro: "From a few product photos to an everyday event, Chorezy is being built to make the shot list, usage, delivery, timing, and budget clear before a local helper offers.",
    highlights: ["Photos, short video, and albums", "Shot list and delivery expectations", "Basic capture and skilled editing help"],
    sections: [
      ["Share the shot list", "Posters can explain the people or products involved, location, schedule, style references, equipment expectations, deliverables, permitted usage, and budget."],
      ["Choose the right level of experience", "A basic photo chore may suit a different helper than event coverage, editing, or specialized equipment work. The scope should make that difference visible."],
      ["Agree on delivery before the task", "File format, quantity, deadline, transfer method, and privacy expectations belong in the chore details—not in a last-minute message."],
    ],
  },
  "holiday-help": {
    slug: "holiday-help",
    path: "/chores/holiday-help/",
    eyebrow: "Holiday-help chores",
    title: "Make seasonal setup and celebrations feel a little lighter.",
    seoTitle: "Local Holiday Decorating & Seasonal Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for local gift wrapping, decorating, baking help, tree setup, event preparation, and seasonal chores.",
    intro: "Holiday lists arrive all at once. Chorezy is being built to help families and local businesses turn decorating, wrapping, baking, and event preparation into well-scoped nearby chores.",
    highlights: ["Gift wrapping and safe decorating", "Baking and event-prep support", "Adult eligibility for heavy or elevated setup"],
    sections: [
      ["Make the seasonal list specific", "Add quantities, materials, photos, indoor or outdoor location, deadline, equipment, access, and budget before selecting a helper."],
      ["Keep elevated and heavy work separate", "Simple wrapping or decorating may suit a Young Helper, while ladders, heavy trees, powered equipment, or large installations may require an eligible Adult Helper or be restricted."],
      ["Finish before the celebration", "Checklists, timing, communication, progress, and completion proof are being designed to stay together in the chore flow."],
    ],
  },
  recycling: {
    slug: "recycling",
    path: "/chores/recycling/",
    eyebrow: "Recycling and cleanup chores",
    title: "Get local help sorting, bagging, and clearing everyday waste.",
    seoTitle: "Local Recycling, Litter & Yard Cleanup Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for nearby recycling sorting, litter pickup, leaf bagging, debris loading, and eligible cleanup chores.",
    intro: "Chorezy is being built to make neighborhood cleanup work easier to define, including what must be sorted, lifted, bagged, transported, or handled by an Adult Helper.",
    highlights: ["Recycling sort and litter pickup", "Leaves, bags, and eligible yard cleanup", "Materials, weight, tools, and disposal plan upfront"],
    sections: [
      ["Describe what is being handled", "Posters can list the materials, estimated volume and weight, bags or bins, tools, pickup location, disposal destination, timing, photos, and budget."],
      ["Flag hazards before offers", "Sharp, chemical, biological, extremely heavy, or otherwise hazardous materials do not belong in a routine chore. Hauling and powered yard tools may require an eligible Adult Helper."],
      ["Keep disposal expectations clear", "The planned flow keeps the checklist, progress, completion proof, receipts where relevant, payment, and reviews with the chore."],
    ],
  },
  "child-care": {
    slug: "child-care",
    path: "/chores/child-care/",
    eyebrow: "Child-care chores",
    title: "Arrange eligible local help for everyday child-care routines.",
    seoTitle: "Local Babysitting & Child-Care Help | Chorezy",
    description: "Join the Chorezy U.S. waitlist for eligible local babysitting, supervised play, homework, snack, meal, and bedtime-support chores.",
    intro: "Chorezy is being designed to make child-care requests explicit about ages, supervision, routines, guardian expectations, timing, and helper eligibility before a family selects anyone.",
    highlights: ["Supervised play and homework support", "Routines, meals, and bedtime details", "Guardian expectations and helper eligibility upfront"],
    sections: [
      ["Share the full care context", "Posters can describe the children’s ages, routine, supervision, allergies, emergency contacts, location, timing, household rules, transportation needs, and budget."],
      ["Treat eligibility as essential", "A suitable supervised activity is different from independent babysitting, transportation, or extended care. Age, verification, guardian controls, local requirements, and launch policy determine eligibility."],
      ["Keep safety tools close to the task", "Chorezy is being designed around in-app communication, active-task reporting, guardian visibility where relevant, and emergency options with a direct 911 fallback."],
    ],
  },
} satisfies Record<string, DiscoveryPageData>;

export const choreDirectory = [
  ["cleaning", "Cleaning", "#009FE3"],
  ["yard-care", "Gardening", "#4CAF50"],
  ["pet-care", "Pet care", "#FF9800"],
  ["car-care", "Car care", "#2196F3"],
  ["food-and-groceries", "Food", "#FFB300"],
  ["tech-help", "Tech help", "#9C27B0"],
  ["art-and-crafts", "Art & crafts", "#E91E63"],
  ["errands", "Delivery", "#009688"],
  ["sports", "Sports", "#3F51B5"],
  ["tutoring", "Tutoring", "#795548"],
  ["home-help", "Home help", "#7CB342"],
  ["senior-care", "Senior care", "#E5484D"],
  ["events", "Events", "#AD1457"],
  ["photography", "Photography", "#607D8B"],
  ["assembly", "Assembly", "#F59E0B"],
  ["holiday-help", "Holiday help", "#F44336"],
  ["recycling", "Recycling", "#558B2F"],
  ["child-care", "Child care", "#FFB020"],
] as const satisfies readonly (readonly [keyof typeof chorePages, string, string])[];

export const earnPages = {
  "young-helpers": {
    slug: "young-helpers",
    path: "/earn/young-helpers/",
    eyebrow: "Young Helpers · ages 14–17",
    title: "A local way for teens to earn with guardian involvement.",
    seoTitle: "Paid Chores for Teens Ages 14–17 | Chorezy",
    description: "Chorezy Young Helpers are ages 14–17. Join the U.S. waitlist for age-appropriate local chore opportunities designed around guardian visibility.",
    intro: "Chorezy is being designed for teens who want to earn after school, on weekends, or during school breaks—without treating Young Helpers like Adult Helpers.",
    highlights: ["For ages 14–17", "Guardian visibility and approval controls", "Age-appropriate eligible chores"],
    sections: [
      ["Built around a distinct helper type", "Young Helper eligibility is designed to remain visible throughout discovery and task participation, with different controls from Adult Helper accounts."],
      ["A practical option during school breaks", "Eligible nearby chores can give teens a structured way to use free time, practice responsibility, and earn within the product’s rules."],
      ["Guardians stay part of the process", "Guardian-linked visibility and approval controls are part of the planned experience. Exact requirements may vary as launch testing continues."],
    ],
  },
  "adult-helpers": {
    slug: "adult-helpers",
    path: "/earn/adult-helpers/",
    eyebrow: "Adult Helpers · ages 18+",
    title: "Find flexible local work that fits around your schedule.",
    seoTitle: "Flexible Local Chore Jobs for Adults | Chorezy",
    description: "Chorezy Adult Helpers are ages 18+. Join the U.S. waitlist to find eligible yard care, errands, pet care, and household chores nearby.",
    intro: "Adult Helpers will be able to discover nearby opportunities, review the work and budget, and make an offer when a chore fits their availability and skills.",
    highlights: ["For ages 18+", "Choose suitable nearby opportunities", "Make an offer before work begins"],
    sections: [
      ["You decide what fits", "Chorezy is being built around opt-in offers rather than automatic job assignment. Review the details before choosing whether to participate."],
      ["Keep the task organized", "Instructions, communication, progress, completion, and payout steps are being designed to stay with the chore."],
      ["Multiple kinds of local work", "Launch categories include yard care, pet care, errands, home help, and other eligible tasks, with availability varying by location."],
    ],
  },
} satisfies Record<string, DiscoveryPageData>;

export const helpPages = {
  "working-families": {
    slug: "working-families",
    path: "/help/working-families/",
    eyebrow: "For working moms and busy families",
    title: "Make room in a full week with trusted local help.",
    seoTitle: "Local Chore Help for Busy Families | Chorezy",
    description: "Chorezy helps working moms and busy U.S. families plan local yard care, pet care, errands, and home help in one chore flow.",
    intro: "When work, school, care, and home all compete for the same hours, even a small chore can stall the week. Chorezy is being built to make asking for nearby help clearer and more manageable.",
    highlights: ["Describe the chore once", "Compare eligible helper offers", "Follow progress in one place"],
    sections: [
      ["Turn mental load into a clear plan", "Add the task, checklist, timing, location, budget, and optional photos or voice context instead of repeating the same instructions across messages."],
      ["Stay in control of the choice", "Compare offers and select the eligible helper who fits the work. Guardian and helper-type information is designed to remain visible where relevant."],
      ["Built for the real task, not just discovery", "Arrival updates, in-app communication, protected payment flows, completion proof, reviews, and safety reporting are part of the product direction."],
    ],
  },
} satisfies Record<string, DiscoveryPageData>;
