export const faqItems = [
  ["What is Chorezy?", "Chorezy is a neighborhood marketplace being built to connect people and local businesses who need help with Young and Adult Helpers nearby."],
  ["Where is Chorezy launching?", "Chorezy is launching in the United States first. Your ZIP code helps us understand where local demand is growing."],
  ["When will Chorezy reach my area?", "We do not have public city-by-city dates yet. Waitlist demand, local helper availability, and launch testing will shape the rollout."],
  ["Why do you need my ZIP code?", "We use your ZIP code to plan local launches where people who need help and eligible helpers can arrive together. We do not ask for your street address on the waitlist."],
  ["How old do helpers need to be?", "Young Helpers are ages 14–17. Adult Helpers are ages 18 and above. Each helper type has distinct eligibility needs, and Young Helper participation is being designed around guardian involvement and age-appropriate work."],
  ["Can teens earn during summer and school breaks?", "That is one of the use cases Chorezy is being designed for. Young Helpers ages 14–17 may be able to explore suitable local chores after school, on weekends, or during school breaks, subject to guardian and task eligibility controls."],
  ["How will Young Helper participation work?", "Young Helper participation is being designed with distinct eligibility rules, guardian visibility, and controls appropriate to the account and task. Exact requirements may change during launch testing."],
  ["What kinds of chores will be available?", "Examples include yard work, pet care, errands, cleaning help, moving assistance, and other local tasks that match a helper's eligibility and skills."],
  ["How will posting a chore work?", "Posters will be able to describe the work, add a checklist and optional photos or voice context, choose a time and location, set a budget, and review eligible helper offers."],
  ["Can I schedule repeating chores?", "Chorezy is being built to support both one-time and repeating chores. Availability may vary by chore type, helper eligibility, and launch area."],
  ["How will offers and payments work?", "Eligible helpers will be able to make offers on nearby chores. Posters can compare those offers and choose a helper, with payment and payout steps handled inside the chore flow."],
  ["Can local businesses join?", "Yes. Local businesses can join the waitlist if they expect to need an extra pair of hands for eligible local tasks."],
  ["How is Chorezy approaching safety?", "The product is being designed around identity and eligibility checks, guardian involvement, in-app communication, protected payment flows, and task-level reporting tools."],
  ["Will Chorezy offer emergency help during an active chore?", "An active-chore emergency flow for police or safety, medical, and fire requests is being integrated and tested, alongside a visible option to call 911 directly. Availability will depend on launch readiness and location; call 911 for immediate danger."],
  ["How does the $5 referral credit work?", "After joining, share your personal link. If two friends join through it and you create your Chorezy account at launch, you may receive $5 in Chorezy credit, subject to the waitlist terms and eligibility checks."],
  ["Does joining cost anything?", "No. Joining the U.S. launch waitlist is free and does not obligate you to use the app."],
] as const;
